mode: debug
host: 127.0.0.1
port: 8080
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  db_name: open-api
  charset: utf8mb4
  prefix: open_
redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  db: 0
  prefix: open_
logger:
  type: file # 记录方式
  path: /logs/ # 项目相对路径，日志文件路径
  filename: open-api.log
  max_size: 10
  max_age: 30
  max_backups: 7