app_debug: true
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  dbname: open-api
  charset: utf8mb4
  prefix: open_
redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  db: 0
  prefix: open_